Repository I4-14/project, pull requests merged in 2024-07, with the labels that each got.

#5 Feat/#1 column
  src/main/java/com/sparta/trello/TrelloApplication.java
  src/main/java/com/sparta/trello/columns/entity/CategoryEnum.java
  src/main/java/com/sparta/trello/columns/entity/Columns.java
  src/main/java/com/sparta/trello/columns/repository/ColumnsRepository.java
  src/main/java/com/sparta/trello/common/Timestamped.java
  src/test/java/com/sparta/trello/TrelloApplicationTests.java
Labels: 🌟feat

#4 Feat/#2 User Entity 초기 세팅
  src/main/java/com/sparta/trello/auth/entity/Role.java
  src/main/java/com/sparta/trello/auth/entity/User.java
  src/main/java/com/sparta/trello/auth/entity/UserStatus.java
  src/main/java/com/sparta/trello/auth/repository/UserRepository.java
Labels: 🌟feat

#7 Column 엔티티 생성
  src/main/java/com/sparta/trello/TrelloApplication.java
  src/main/java/com/sparta/trello/columns/entity/CategoryEnum.java
  src/main/java/com/sparta/trello/columns/entity/Columns.java
  src/main/java/com/sparta/trello/columns/repository/ColumnsRepository.java
  src/main/java/com/sparta/trello/common/Timestamped.java
Labels: 🌟feat

#11 Card 초기세팅
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/java/com/sparta/trello/card/repository/CardRepository.java
  src/main/java/com/sparta/trello/columns/entity/Columns.java
Labels: 🌟feat

#13 Feat/#2 auth UserDetails 추가
  src/main/java/com/sparta/trello/auth/entity/Role.java
  src/main/java/com/sparta/trello/auth/entity/User.java
  src/main/java/com/sparta/trello/auth/entity/UserStatus.java
  src/main/java/com/sparta/trello/auth/repository/UserRepository.java
  src/main/java/com/sparta/trello/auth/repository/UserRepositoryCustom.java
  src/main/java/com/sparta/trello/auth/repository/UserRepositoryImpl.java
  src/main/java/com/sparta/trello/auth/security/UserDetailsImpl.java
  src/main/java/com/sparta/trello/auth/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/java/com/sparta/trello/columns/entity/Columns.java
  src/main/java/com/sparta/trello/config/QueryDSLConfig.java
  src/main/resources/application.properties
Labels: 🌟feat

#17 Feat/#9 card 기능 구현
  src/main/java/com/sparta/trello/card/controller/CardController.java
  src/main/java/com/sparta/trello/card/dto/CardCreateRequestDto.java
  src/main/java/com/sparta/trello/card/dto/CardResponseDto.java
  src/main/java/com/sparta/trello/card/dto/CardSearchCondDto.java
  src/main/java/com/sparta/trello/card/dto/CardUpdateCardStatusRequestDto.java
  src/main/java/com/sparta/trello/card/dto/CardUpdateRequestDto.java
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/java/com/sparta/trello/card/repository/CardCustomRepository.java
  src/main/java/com/sparta/trello/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/sparta/trello/card/repository/CardRepository.java
  src/main/java/com/sparta/trello/card/service/CardService.java
  src/main/java/com/sparta/trello/columns/entity/Columns.java
Labels: 🌟feat

#18 Feat/#2 auth 사용자 인증 기능 추가
  src/main/java/com/sparta/trello/auth/controller/AuthController.java
  src/main/java/com/sparta/trello/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/trello/auth/dto/LoginResponseDto.java
  src/main/java/com/sparta/trello/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/trello/auth/dto/SignupResponseDto.java
  src/main/java/com/sparta/trello/auth/entity/User.java
  src/main/java/com/sparta/trello/auth/security/UserDetailsImpl.java
  src/main/java/com/sparta/trello/auth/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/trello/auth/service/AuthService.java
  src/main/java/com/sparta/trello/config/SecurityConfig.java
  src/main/java/com/sparta/trello/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/trello/jwt/JwtUtil.java
  src/main/resources/application.properties
Labels: 🌟feat

#19 Feat/#10 comment 기능구현
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/java/com/sparta/trello/columns/entity/Columns.java
  src/main/java/com/sparta/trello/comment/controller/CommentController.java
  src/main/java/com/sparta/trello/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/trello/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/trello/comment/entity/Comment.java
  src/main/java/com/sparta/trello/comment/repository/CommentCustomRepository.java
  src/main/java/com/sparta/trello/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/sparta/trello/comment/repository/CommentRepository.java
  src/main/java/com/sparta/trello/comment/service/CommentService.java
Labels: 🌟feat

#26 Fix/#23 auth role 사용자 인증 권한 및 응답 데이터 형식 수정
  src/main/java/com/sparta/trello/auth/controller/AuthController.java
  src/main/java/com/sparta/trello/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/trello/auth/service/AuthService.java
  src/main/java/com/sparta/trello/common/ApiResponse.java
  src/main/java/com/sparta/trello/common/exception/CustomException.java
  src/main/java/com/sparta/trello/common/exception/ErrorEnum.java
  src/main/java/com/sparta/trello/common/exception/ExceptionDto.java
  src/main/java/com/sparta/trello/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/trello/common/jwt/AccessDeniedHandlerImpl.java
  src/main/java/com/sparta/trello/common/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/trello/common/jwt/JwtUtil.java
  src/main/java/com/sparta/trello/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: 🩹fix

#32 Fix/#23 auth 예외처리 공통설정 및 주석, 컨벤션 수정
  src/main/java/com/sparta/trello/auth/controller/AuthController.java
  src/main/java/com/sparta/trello/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/trello/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/trello/auth/dto/SignupResponseDto.java
  src/main/java/com/sparta/trello/auth/dto/TokenResponseDto.java
  src/main/java/com/sparta/trello/auth/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/trello/auth/service/AuthService.java
  src/main/java/com/sparta/trello/common/exception/ErrorEnum.java
  src/main/java/com/sparta/trello/common/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/trello/common/jwt/JwtUtil.java
Labels: 🌟feat, 🩹fix

#33 Feat/#29 frontend card,comment구현
  src/main/java/com/sparta/trello/card/controller/CardController.java
  src/main/java/com/sparta/trello/card/dto/CardDetailsResponseDto.java
  src/main/java/com/sparta/trello/card/service/CardService.java
  src/main/java/com/sparta/trello/comment/controller/CommentController.java
  src/main/java/com/sparta/trello/config/SecurityConfig.java
  src/main/java/com/sparta/trello/view/ViewController.java
  src/main/resources/templates/createCard.html
  src/main/resources/templates/index.html
  src/main/resources/templates/readCard.html
Labels: 🌟feat

#36 Fix/#35 cardservice 오류수정
  src/main/java/com/sparta/trello/card/dto/CardDetailsResponseDto.java
  src/main/java/com/sparta/trello/card/service/CardService.java
Labels: 🩹fix

#37 Fix/#35 cardservice 오류수정
  src/main/java/com/sparta/trello/card/service/CardService.java
Labels: 🩹fix

#38 Fix/#25 card 응답형식,예외처리 수정
  src/main/java/com/sparta/trello/card/controller/CardController.java
  src/main/java/com/sparta/trello/card/repository/CardRepository.java
  src/main/java/com/sparta/trello/card/service/CardService.java
  src/main/java/com/sparta/trello/common/exception/ErrorEnum.java
Labels: 🩹fix

#42 Fix/#41 응답형식 수정 후 프론트 오류로 재수정
  src/main/java/com/sparta/trello/view/ViewController.java
  src/main/resources/templates/readCard.html
Labels: 🩹fix

#45 Fix/#45 frontend dto id 추가
  src/main/java/com/sparta/trello/card/dto/CardResponseDto.java
Labels: 🩹fix

#46 Feat/#44 kanbanboard to card detail
  src/main/resources/templates/createColumn.html
  src/main/resources/templates/kanbanboard.html
  src/main/resources/templates/updateColumn.html
Labels: 🌟feat, 🩹fix

#48 Refactor/#40 auth 중복 코드 수정
  src/main/java/com/sparta/trello/auth/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/trello/auth/service/AuthService.java
  src/main/java/com/sparta/trello/common/jwt/JwtAuthorizationFilter.java
Labels: ♻️refactor, 🩹fix

#49 index 수정모드 구현
  src/main/java/com/sparta/trello/view/ViewController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/updateBoard.html
Labels: 🌟feat, 🩹fix

#54 Fix/#53 카드 상세조회시 작업자 추가
  src/main/java/com/sparta/trello/card/controller/CardController.java
  src/main/java/com/sparta/trello/card/dto/CardCreateRequestDto.java
  src/main/java/com/sparta/trello/card/dto/CardDetailsResponseDto.java
  src/main/java/com/sparta/trello/card/dto/CardResponseDto.java
  src/main/java/com/sparta/trello/card/dto/CardSearchCondDto.java
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/java/com/sparta/trello/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/sparta/trello/card/service/CardService.java
  src/main/java/com/sparta/trello/comment/controller/CommentController.java
  src/main/java/com/sparta/trello/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/trello/comment/entity/Comment.java
  src/main/java/com/sparta/trello/comment/service/CommentService.java
  src/main/java/com/sparta/trello/view/ViewController.java
  src/main/resources/templates/createCard.html
  src/main/resources/templates/moveCard.html
  src/main/resources/templates/readCard.html
Labels: 🩹fix

#51 Fix/#9 card,comment 권한설정 및 순서이동 요청값 수정
  src/main/java/com/sparta/trello/card/controller/CardController.java
  src/main/java/com/sparta/trello/card/dto/CardDetailsResponseDto.java
  src/main/java/com/sparta/trello/card/dto/CardResponseDto.java
  src/main/java/com/sparta/trello/card/dto/CardSearchCondDto.java
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/java/com/sparta/trello/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/sparta/trello/card/service/CardService.java
  src/main/java/com/sparta/trello/comment/controller/CommentController.java
  src/main/java/com/sparta/trello/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/trello/comment/entity/Comment.java
  src/main/java/com/sparta/trello/comment/service/CommentService.java
Labels: 🩹fix

#58 Refactor/#40 auth 코드 수정
  src/main/java/com/sparta/trello/auth/service/AuthService.java
  src/main/java/com/sparta/trello/card/dto/CardResponseDto.java
Labels: 🩹fix

#60 Fix/#59 카드 생성시 토큰 추가, 카드안에 유저이름 추가, 칸반보드 색 수정
  src/main/java/com/sparta/trello/card/dto/CardResponseDto.java
  src/main/java/com/sparta/trello/card/dto/CardUpdateRequestDto.java
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/java/com/sparta/trello/card/service/CardService.java
  src/main/java/com/sparta/trello/columns/entity/Columns.java
  src/main/java/com/sparta/trello/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/trello/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/sparta/trello/view/ViewController.java
  src/main/resources/templates/createCard.html
  src/main/resources/templates/kanbanboard.html
Labels: 🩹fix

#66 Fix/#65 header 토큰 추가, 접근권한 alert
  src/main/resources/templates/readCard.html
Labels: 🩹fix

#64 ✨ update : http API 테스트 파일 추가
  http/Invite.http
  http/auth.http
  http/board.http
  http/card.http
  http/columns.http
  http/comment.http
Labels: 🌟feat

#75 Fix/#74 카드조회시 작업자 수정
  src/main/java/com/sparta/trello/card/dto/CardDetailsResponseDto.java
  src/main/java/com/sparta/trello/card/dto/CardResponseDto.java
  src/main/java/com/sparta/trello/card/dto/CardSearchCondDto.java
  src/main/java/com/sparta/trello/card/dto/CardUpdateRequestDto.java
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/java/com/sparta/trello/card/service/CardService.java
  src/main/resources/templates/createCard.html
  src/main/resources/templates/readCard.html
Labels: 🩹fix

#73 Feat/#62 http test 보드 초대 수정
  http/Invite.http
  http/auth.http
Labels: 🩹fix

#77 Fix/#76 카드상세조회 및 작업자별 조회시 username -> userId 변경
  src/main/java/com/sparta/trello/card/controller/CardController.java
  src/main/java/com/sparta/trello/card/dto/CardResponseDto.java
  src/main/java/com/sparta/trello/card/dto/CardUpdateCardStatusRequestDto.java
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/java/com/sparta/trello/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/sparta/trello/card/service/CardService.java
  src/main/java/com/sparta/trello/comment/repository/CommentRepository.java
  src/main/resources/templates/readCard.html
Labels: 🩹fix

#79 Feat/#62 http test api 수정
  http/card.http
  http/columns.http
Labels: 🩹fix

#80 Feat/#15 frontend 수정
  src/main/java/com/sparta/trello/view/ViewController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/kanbanboard.html
  src/main/resources/templates/readCard.html
Labels: 🩹fix

#81 Refactor/#68 query 최적화
  src/main/java/com/sparta/trello/auth/entity/User.java
  src/main/java/com/sparta/trello/board/controller/BoardController.java
  src/main/java/com/sparta/trello/board/entity/Board.java
  src/main/java/com/sparta/trello/board/repository/BoardRepository.java
  src/main/java/com/sparta/trello/board/repository/BoardRepositoryCustom.java
  src/main/java/com/sparta/trello/board/repository/BoardRepositoryImpl.java
  src/main/java/com/sparta/trello/board/service/BoardService.java
  src/main/java/com/sparta/trello/boardworkspace/repository/BoardWorkspaceRepositoryImpl.java
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/java/com/sparta/trello/card/repository/CardCustomRepositoryImpl.java
  src/main/java/com/sparta/trello/columns/entity/Columns.java
  src/main/java/com/sparta/trello/columns/repository/ColumnsCustomRepositoryImpl.java
  src/main/java/com/sparta/trello/comment/repository/CommentCustomRepositoryImpl.java
Labels: ♻️refactor

#83 컬럼 생성, 수정, 삭제와 카드 순서이동이 안되는 문제 해결
  src/main/java/com/sparta/trello/card/entity/Card.java
  src/main/resources/templates/createColumn.html
  src/main/resources/templates/updateColumn.html
Labels: bug, 🩹fix
